blas_impl:
  - netlib
  - openblas
  - mkl          # [x86 or x86_64]
  - blis         # [x86 or x86_64]
# the following do not affect CI generation (needs to be done manually)
# but are represented "philosophically speaking" for reference
jit_state:                  # [ppc64le and (python_impl == "pypy")]
  - on                      # [ppc64le and (python_impl == "pypy")]
  - off                     # [ppc64le and (python_impl == "pypy")]
set_openblas_threads:       # [win and (blas_impl == "openblas")]
  - DUMMY=1                 # [win and (blas_impl == "openblas")]
  - OPENBLAS_NUM_THREADS=1  # [win and (blas_impl == "openblas")]
